### ISSUE TITLE
Include new features from WireViz v0.2

### ISSUE THREAD

**Issue by 17o2** [slightlynybbled/wireviz-gui#1]
Hi,

this is just a heads up. v0.2 is _not yet_ released, but I've started putting together a [change log](https://github.com/formatc1702/WireViz/blob/dev/CHANGELOG.md) in an attempt to track the [user-relevant] changes that have been building up.
Please be aware some of the listed changes _have not_ been implemented yet, but I am aiming to implement them before releasing v0.2.
I thought I would bring this to your attention, so you are not overwhelmed when the new version is actually released.

Cheers!

**Comment by slightlynybbled** [comment]
Thanks for the heads up.

Since `v0.1.0` doesn't have the features I need, I have been keeping up with the dev branch anyway.  As you implement your changes, I will update within a few hours.

**Comment by 17o2** [comment]
As you may have seen, I've added the [v0.2 milestone](https://github.com/formatc1702/WireViz/milestone/1) and we're moving close to completion! I'll try not to let feature creep kick in and stick to the issues and PRs that are there currently.

😎

**Comment by 17o2** [comment]
Another heads up: it's 3 months after my last post, but v0.2 was finally released! ;-) Thought you would like to know!

**Comment by slightlynybbled** [comment]
Thanks for the ping!  I have dropped off the face of the earth for the past couple of months.  Life, you know.

I will do some work to get the v0.2 integrated.

**Comment by 17o2** [comment]
> I have dropped off the face of the earth for the past couple of months. Life, you know.

Tell me about it. Same for me.

> I will do some work to get the v0.2 integrated.

Don't feel rushed!

---

Regarding the open issue [123](https://github.com/formatc1702/WireViz/pull/123) for WireViz, whenever you have time let us know if you are able to take care of it, or if me and the other contributors should take over. :)

**Comment by slightlynybbled** [comment]
Have integrated basic features from v0.2 into wireviz-gui
